[package]
name = "ch32v003"
version = "0.1.0"
edition = "2024"

[dependencies]
ch32-hal = { git = "https://github.com/ch32-rs/ch32-hal",
    version = "0.1.0",
    features = ["ch32v003f4u6","memory-x","embassy","time-driver-tim2","rt"]
}
embassy-embedded-hal = "0.6.0"
embassy-executor = { version = "0.10.0", features = [
    "platform-spin",
    "executor-thread",
] }
embassy-sync = "0.8.0"
embassy-time = "0.5.1"

# This is okay because we should automatically use whatever ch32-hal uses
qingke = "0.7"
qingke-rt = { version = "0.7", features=["highcode"] }

embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"

portable-atomic = "1.14.0"

[profile.release]
opt-level = "z"        # try "s" too — sometimes wins
lto = "fat"
codegen-units = 1
panic = "abort"
debug = 2              # free: DWARF isn't ALLOC, never reaches flash
overflow-checks = false
debug-assertions = false
incremental = false
strip = false          # keep symbols for wlink regs → dpc lookup

[profile.dev]
overflow-checks = false

